### ISSUE TITLE
smc-util/syncstring → SyncDoc →  _handle_patch_update: @_doc?.is_equal is not a function

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1873]
This is a regression (or only a partial fix) introduced by 3437690f

`r.is_equal is not a function`

```
TypeError: r.is_equal is not a function
    at t._handle_patch_update (https://cloud.sagemath.com/static/smc-5d8110c797843a159773.js?5d8110c797843a159773:54:11988)
    at t.<anonymous> (https://cloud.sagemath.com/static/smc-5d8110c797843a159773.js?5d8110c797843a159773:53:9473)
    at t.emit (https://cloud.sagemath.com/static/smc-5d8110c797843a159773.js?5d8110c797843a159773:30:14675)
    at https://cloud.sagemath.com/static/smc-5d8110c797843a159773.js?5d8110c797843a159773:140:3129
    at l (https://cloud.sagemath.com/static/smc-5d8110c797843a159773.js?5d8110c797843a159773:13:8014)
    at function.e._wrapper.e._wrapper (https://cloud.sagemath.com/static/lib-5d8110c797843a159773.js?5d8110c797843a159773:118:28349)
    at https://cloud.sagemath.com/static/lib-5d8110c797843a159773.js?5d8110c797843a159773:118:29869
```

top frame:

```
this._save(),n=this._patch_list.value(),(null!=(r=this._doc)?r.[BANG]is_equal(n):void 0)?void 0:(this._last=this._doc=n,this.emit("change"))}
```

which is in `smc-util/syncstring.coffee`

```
_handle_patch_update: (changed_keys) =>
    [ ... ]
    # if document changed, set to new version
    if not @_doc?.is_equal(new_remote)
        @_last = @_doc = new_remote
        @emit('change')

```

time: 10 min

**Comment by haraldschilly** [comment]
I tried to figure out what's going on, but no real clue. I assume `set_doc` sets `@_doc` to something unexpected.

time: 10 min

**Comment by williamstein** [comment]
I'm going to put in a hotfix, as this is extremely important.

**Comment by williamstein** [comment]
hotfix pushed live now.

**Comment by haraldschilly** [comment]
Ok, let's keep this open. For some context, most of the errors happen with sagews files (only one tex and one ipynb). So, my theory, it could be sagews specific and those two outliers did happen in the background while switching to another tab?

**Comment by williamstein** [comment]
Note that with the code change I made, there is no way this stacktrace will happen again... but the test I put in is masking some confusion/misunderstanding in the code.

**Comment by williamstein** [comment]
I think I fixed this.
